"""Remove song_jacket_id

Revision ID: d50b71afc01f
Revises: 47f7b1a2150b
Create Date: 2026-04-01 22:24:07.989951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50b71afc01f'
down_revision: Union[str, Sequence[str], None] = '47f7b1a2150b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'song_jacket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('song_jacket_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
